name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: login to dockerhub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login registry.cn-hangzhou.aliyuncs.com -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: sync image
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "oldthreefeng"
        git config --global user.email "daoren@gaoding.com"
        git remote -v
        echo 123 > test.txt
        git add . && git commit -m "by workflow" && git checkout -b v2.0.3 && git push origin v2.0.3
